name: "minikube"
description: "test your app against real kubernetes."
author: 'Medya Gh'
inputs:
  action: # id of input
    description: "minikube command to run, could be start, pause, unpause, stop, status."
    required: false
    default: "start"
  driver:
    description: "which driver to user, options are docker, none, and podman"
    required: false
    default: "docker"
runs:
  using: 'node12'
  main: 'dist/index.js'
