name: 'setup-minikube'
description: 'test your app against real Kubernetes.'
author: 'Medya Gh'
branding:
  icon: 'box'  
  color: 'blue'
inputs:
  minikube-version:
    description: 'Choose a specific version of minikube'
    required: false
    default: 'latest'
  action:
    description: 'minikube command to run, could be start, pause, unpause, stop, status.'
    required: false
    default: 'start'
  driver:
    description: 'Choose a specific driver, one of: docker, none, podman, virtualbox, parallels, vmwarefusion, hyperkit, vmware, ssh'
    required: false
    default: ''
  container-runtime:
    description: 'Choose a specific container-runtime, one of: docker, containerd, cri-o'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
