name: "auto-tag-latest"
on:
  release:
    types: [published]
jobs:
  auto-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - run: |
          git push --delete origin latest
          git tag latest ${{ github.ref_name }}
          git push origin latest
