name: "auto-tag-latest"
on:
  release:
    types: [published]
jobs:
  auto-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - run: |
          git push --delete origin latest
          git tag latest ${{ github.ref_name }}
          git push origin latest
