name: "auto-tag-latest"
on:
  release:
    types: [published]
jobs:
  auto-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - run: |
          git push --delete origin latest
          git tag latest ${{ github.ref_name }}
          git push origin latest
