name: "auto-tag-latest"
on:
  release:
    types: [published]
jobs:
  auto-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      - run: |
          git push --delete origin latest
          git tag latest ${{ github.ref_name }}
          git push origin latest
